In [2]:
# Import pytorch
import torch

In [3]:
def activation(x):
    #sigmoid function
    return 1/(1+torch.exp(-x))

In [4]:
###Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# features are 3 random normal variables
features = torch.randn((1,5))

# True weights for our data, random normal variables again
weights = torch.randn_like(features)

# and a true bias term
bias = torch.randn((1,1))

In [5]:
### Solution

y = activation(torch.sum(features*weights) + bias)
y = activation((features*weights).sum() + bias)

In [6]:
features.shape

torch.Size([1, 5])

In [8]:
weights_0 = weights.reshape(5,1)

In [10]:
weights_0.shape

torch.Size([5, 1])

In [11]:
weights_re = weights.resize_(5,1)
weights_re.shape

torch.Size([5, 1])

Exercise: Calculate the output of our little network using matrix multiplication.

In [13]:
# Solution
y = activation(torch.mm(features, weights.view(5,1)) + bias)

### Stack them up!

That's how you can calculate the output for a single neuron. The real power of this algorithm happens when you start stacking these individual units into layers and stacks of layers, into a network of neurons. The output of one layer of neurons becomes the input for the next layer. With multiple input units and output units, we now need to express the weights as a matrix.

<img src='assets/multilayer_diagram_weights.png' width=450px>

The first layer shown on the bottom here are the inputs, understandably called the **input layer**. The middle layer is called the **hidden layer**, and the final layer (on the right) is the **output layer**. We can express this network mathematically with matrices again and use matrix multiplication to get linear combinations for each unit in one operation. For example, the hidden layer ($h_1$ and $h_2$ here) can be calculated 

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$

The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

In [16]:
## Generate some random data
torch.manual_seed(7)

features = torch.randn((1,3))

# Define size of each layer in our network
n_input = features.shape[1]    # Number of input units, must match number of input features
n_hidden = 2                   # Number of hidden units
n_output = 1                   # Number of output units

In [17]:
# Weights for input to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden to output
W2 = torch.randn(n_hidden, n_output)

In [18]:
# bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

> **Exercise:** Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`.    

In [19]:
### Solution
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


## Numpy to Torch and back

Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [20]:
import numpy as np


In [21]:
a = np.random.rand(4,3)
a

array([[0.7203688 , 0.43293913, 0.13719874],
       [0.80412395, 0.50574394, 0.41825531],
       [0.12033716, 0.50917296, 0.22785301],
       [0.60690973, 0.47386543, 0.77232882]])

In [23]:
b = torch.from_numpy(a)
b

tensor([[0.7204, 0.4329, 0.1372],
        [0.8041, 0.5057, 0.4183],
        [0.1203, 0.5092, 0.2279],
        [0.6069, 0.4739, 0.7723]], dtype=torch.float64)

In [24]:
b.numpy()

array([[0.7203688 , 0.43293913, 0.13719874],
       [0.80412395, 0.50574394, 0.41825531],
       [0.12033716, 0.50917296, 0.22785301],
       [0.60690973, 0.47386543, 0.77232882]])

In [25]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.4407, 0.8659, 0.2744],
        [1.6082, 1.0115, 0.8365],
        [0.2407, 1.0183, 0.4557],
        [1.2138, 0.9477, 1.5447]], dtype=torch.float64)

In [26]:
# Numpy array matches new values from Tensor
a

array([[1.44073759, 0.86587826, 0.27439748],
       [1.60824791, 1.01148788, 0.83651063],
       [0.24067432, 1.01834592, 0.45570602],
       [1.21381945, 0.94773087, 1.54465764]])